title: IHPCSS Wiki
description: International HPC Summer School

wiki_folder: wiki

# Sidebar
show_downloads: false
git_branch: master
logo_url: /assets/images/ihpcss-logo.png

custom_head: false
custom_sidebar: true
custom_footer: false

theme:

use_github_wiki: false
use_prose_io: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
#  - jgemoji
#  - jekyll-mentions
